### ISSUE TITLE
Can't run unittest for test_email.py

### ISSUE THREAD

**Issue by oimartin** [dictybase-playground/learn-github-action#20]
VS code doesn't recognize the tests that I created. I'm assuming there's an issue with how I setup the class and the variables with self.

https://github.com/dictybase-playground/learn-github-action/blob/feat/send-email/tests/test_email.py

I'm going to spend time looking at this article: https://realpython.com/python-testing/  and the documentation of unit tests more

**Comment by cybersiddhu** [comment]
Look here https://realpython.com/testing-third-party-apis-with-mocks/
You don't need to use `nose` package

**Comment by cybersiddhu** [comment]
also use `namedtuple` for passing more than two parameters to any methods.

**Comment by oimartin** [comment]
1. Refactor code to use named tuple for modules that have more than 2 parameters
2. Create api url command line prompt
3. Use the mock library to test send_email() module
